### ISSUE TITLE
[bitbucket] support for alternate registry pull credentials

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-convert#10]
Bitbucket supports providing registry pull credentials as username and password:

```yaml
image:
  name: us-east1-docker.pkg.dev/my-project/my-repo/test-image:latest
  username: $DOCKER_REGISTRY_USERNAME
  password: $DOCKER_REGISTRY_PASSWORD
```

Or by providing aws access key and secret:

```yaml
image:
  name: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/bash:latest
  aws: 
    access-key: $AWS_ACCESS_KEY
    secret-key: $AWS_SECRET_KEY
```

Or through OIDC:

```
image:
  name: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/bash:latest
  aws: 
    oidc-role: arn:aws:iam::<aws_account_id>:role/<your_role_name>
```

Harness currently only supports authentication through connectors.  It is difficult to convert the Bitbucket model to Harness connectors.  Drone and Circle will face similar conversion problems.  We should support docker registry authentication using secrets, as well as connectors, to enable more seamless conversion.

Learn more here:
https://support.atlassian.com/bitbucket-cloud/docs/docker-image-options/
