### ISSUE TITLE
[drone] json in step fails to convert

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#101]
Here is an example pipeline with a plugin step that contains json
```yaml
kind: pipeline
type: docker
name: default

steps:

  - name: example
    image: example
    settings:
      first: foo
      second: bar
      json: {"one":{"two": ["AAA", "BBB"], "three":"value"}}
      third:
        from_secret: top_secret
    environment:
      SECRET:
        from_secret: sensitive
```

Conversion fails with this error

```yaml
2023/05/25 09:15:03 error marshaling into JSON: json: unsupported type: map[interface {}]interface {}
```
