### ISSUE TITLE
[downgrade] `Plugin` steps missing `identifier` and `name`

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#106]
Downgraded plugin steps are missing `identifier` and `name` fields.

For example, this is invalid:

```yaml
          - step:
              spec:
                image: plugins/slack
                settings:
                  channel: ABCDEFG123
              timeout: ""
              type: Plugin
```

This is valid:

```yaml
          - step:
              identifier: slack
              name: slack
              spec:
                image: plugins/slack
                settings:
                  channel: ABCDEFG123
              timeout: ""
              type: Plugin
```

Not all v1 yaml steps will have names to use when downgrading to v0 yaml. When a step doesn't have a name, we should insert a unique name and ID (perhaps based on array position).
