### ISSUE TITLE
[drone] secrets can contain invalid characters

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#107]
Drone secrets can contain characters such as hyphens, which are not allowed for secrets in Harness CI.

For example, this is a valid Drone pipeline:

```yaml
kind: pipeline
type: docker
name: default

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: MY-SLACK-WEBHOOK
```

In Harness CI, we must translate invalid characters to a valid character, such as `_`.

The above yaml should translate to this v1 Harness CI yaml:

```yaml
options: {}
stages:
- name: default
  spec:
    clone: {}
    runtime:
      spec: {}
      type: machine
    steps:
    - name: slack
      spec:
        image: plugins/slack
        with:
          webhook: <+ secrets.getValue("MY_SLACK_WEBHOOK") >
      type: plugin
  type: ci
```

We should verify what characters are valid (likely `[a-zA-Z0-9_]`) in Harness CI yaml, and handle converting them to a safe character (likely `_`).

When this work is done, we will need a follow-up in `harness-migrate` to do the same conversion when reading secrets from the Drone database.
