### ISSUE TITLE
[bitbucket] how to convert multiple pipelines in the same yaml

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-convert#11]
Bitbucket supports defining multiple Pipelines in the same yaml. They choose the best pipeline that matches the Git reference (branch, pull request, etc) and fallback to the _default_ pipeline when there are no other matches.  The current conversion utility only converts the default pipeline.  We need to figure out how to automate conversion of a Bitbucket yaml with multiple pipelines and mirror their same behavior.

```yaml
pipelines:
  default:
  - step:
      name: default
      script:
      - echo default pipeline
  branches:
    master:
    - step:
        name: branch
        script:
        - echo branch pipeline
```
