### ISSUE TITLE
[downgrade] `envs` variables in `plugin` steps are discarded

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#115]
Here is a v1 pipeline with variables set via `envs` in a `plugin` step:

```yaml
options: {}
stages:
- name: default
  spec:
    clone: {}
    runtime:
      spec: {}
      type: machine
    steps:
    - name: publish
      spec:
        envs:
          PASSWORD: <+secrets.getValue("PASSWORD")>
          USERNAME: <+secrets.getValue("USERNAME")>
        image: plugins/example
        pull: always
        with:
          tag: 1.0
      type: plugin
  type: ci
```

When downgrading to v0, the variables are lost.

```yaml
o-convert downgrade example
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: default
      name: default
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: publish
              name: publish
              spec:
                image: plugins/example
                imagePullPolicy: Always
                settings:
                  tag: "1"
              timeout: ""
              type: Plugin
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```

The v1 yaml should downgrade to this:

```yaml
o-convert downgrade example
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: default
      name: default
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: publish
              name: publish
              spec:
                envVariables:
                  PASSWORD: <+secrets.getValue("PASSWORD")>
                  USERNAME: <+secrets.getValue("USERNAME")>
                image: plugins/example
                imagePullPolicy: Always
                settings:
                  tag: "1"
              timeout: ""
              type: Plugin
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```
