### ISSUE TITLE
[drone] `DRONE_` and `CI_` variable references must convert to a Harness expressions

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#117]
Drone provides many variables that can be referenced in pipelines, see https://docs.drone.io/pipeline/environment/reference/ and https://github.com/drone/runner-go/blob/master/environ/environ.go

Harness CI does not support environment variables outside of shell command execution, so we must convert them to expressions.

Here is an example Drone pipeline:

```yaml
name: default
type: docker
kind: pipeline

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: gcr.io/example/repo
      tag: 1.0.${DRONE_BUILD_NUMBER}
      prtag: pr${DRONE_PULL_REQUEST}-${DRONE_BUILD_NUMBER}
```

This should convert to this v1 yaml:

```yaml
options: {}
stages:
- name: default
  spec:
    clone: {}
    runtime:
      spec: {}
      type: machine
    steps:
    - name: publish
      spec:
        image: plugins/docker
        with:
          prtag: pr<+trigger.prNumber>-<+pipeline.sequenceId>
          repo: gcr.io/example/repo
          tag: 1.0.<+pipeline.sequenceId>
      type: plugin
  type: ci
```

Here are a few examples:

| Drone variable | Harness expression |
|----------------|--------------------|
|`DRONE_BUILD_NUMBER`|`<+pipeline.sequenceId>`|
|`DRONE_COMMIT_SHA`|`<+codebase.commitSha>`|
|`DRONE_PULL_REQUEST`|`<+trigger.prNumber>`|
|`DRONE_REMOTE_URL`|`<+codebase.repoUrl>`|
|`DRONE_REPO_NAME`|`<+codebase.repoUrl.split('/')[4]>`|

Relevant Harness documentation:

- https://developer.harness.io/docs/platform/variables-and-expressions/harness-variables/
- https://developer.harness.io/docs/platform/pipelines/w_pipeline-steps-reference/triggers-reference/

Where possible, we should reference `codebase.*` values, since they are always available to pipelines with a codebase defined. `trigger.*` values are not available for manual pipeline executions.
