### ISSUE TITLE
[drone] multiple anchor references fail

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#12]
## Steps to reproduce

1. Create `example.yml`
   ```yaml
   kind: pipeline
   type: docker
   name: default

   anchors:
     - &first_anchor
       FIRST_VAR: value
     - &second_anchor
       SECOND_VAR: value

   steps:
     - name: hello
       image: busybox
       environment:
         <<: *first_anchor
         <<: *second_anchor
       commands:
       - echo hello

   trigger:
     branch:
     - main
   ```
2. Run `go-convert`
   ```
   go-convert drone example.yml
   2023/03/13 16:50:27 yaml: unmarshal errors:
     line 16: mapping key "<<" already defined at line 15
   ```
