### ISSUE TITLE
[downgrade] support converting reports paths

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#121]
Here is v1 yaml with a report path:
```yaml
stages:
- name: example
  spec:
    platform:
      arch: amd64
      os: linux
    runtime:
      spec: {}
      type: cloud
    steps:
    - spec:
        run: echo "Run my tests"
      type: script
    - name: store_test_results
      spec:
        reports:
        - path:
          - test-results/*.xml
          type: junit
        run: echo upload unit test results
      type: script
  type: ci
version: 1
```
This is the current downgraded result:
```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: example
      name: example
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              spec:
                command: echo "Run my tests"
              timeout: ""
              type: Run
          - step:
              identifier: storetestresults
              name: store_test_results
              spec:
                command: echo upload unit test results
              timeout: ""
              type: Run
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```
It should downgrade to this:
```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: example
      name: example
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              spec:
                command: echo "Run my tests"
              timeout: ""
              type: Run
          - step:
              identifier: storetestresults
              name: store_test_results
              spec:
                command: echo upload unit test results
                reports:
                  type: JUnit
                  spec:
                    paths:
                    - test-results/*.xml
              timeout: ""
              type: Run
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```
