### ISSUE TITLE
[downgrade] plugin settings containing lists convert to strings

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#122]
Here is a v1 pipeline
```yaml
name: default
options: {}
stages:
- name: default
  spec:
    clone: {}
    runtime:
      spec: {}
      type: machine
    steps:
    - name: publish
      spec:
        image: plugins/docker
        with:
          list:
          - first
          - second
          - third
          repo: gcr.io/example/repo
      type: plugin
  type: ci
version: 1
```
Currently this converts to this v0 pipeline
```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: default
      name: default
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: publish
              name: publish
              spec:
                image: plugins/docker
                settings:
                  list: '[first second third]'
                  repo: gcr.io/example/repo
              timeout: ""
              type: Plugin
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```
The `list` parameter that contained a list is converted to a string, which would not work as expected at runtime.

The v1 yaml above should convert to this v0 yaml
```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: default
      name: default
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: publish
              name: publish
              spec:
                image: plugins/docker
                settings:
                  list:
                  - first
                  - second
                  - third
                  repo: gcr.io/example/repo
              timeout: ""
              type: Plugin
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```
I have tested this in a prod pipeline, lists are allowed for plugin settings.
