### ISSUE TITLE
[circle] pipeline should not require workflow

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#123]
This is a valid circle pipeline:
```yaml
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: cimg/node:16.19.1-browsers

    working_directory: ~/repo

    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm ci
      - run: |
          node bin/transifex/restructure.js
          git diff --exit-code -- transifex/strings_en.json
      - run: npm run lint
      - run: npm run test
```
Conversion fails with `no workflows defined`.

Our conversion shouldn't require a workflow.

**Comment by bradrydzewski** [comment]
how does Circle behave when there are 2+ jobs, but no workflows?

the reason I ask is that in yaml, the order of map variables are not guarantees.  so wondering how circle handles a scenario where multipl jobs are defined, but without any guarantee in ordering (at least per the yaml spec)

**Comment by jimsheldon** [comment]
I just tried with this pipeline

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: build
          command: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: test
          command: echo "this is the test job"
```
This is the result https://app.circleci.com/pipelines/github/jimsheldon/sandbox/9/workflows/e4870d97-9c21-47af-8211-c2a83844b889/jobs/10

It appears only the first job ran.

I opened this issue after trying to convert this pipeline https://github.com/getodk/central-frontend/blob/master/.circleci/config.yml, which only has one job.

Perhaps we should support converting the first job when there are no workflows?
