### ISSUE TITLE
[circle] add support for `shell`

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#125]
Circle supports setting `shell`:

https://circleci.com/docs/configuration-reference/#default-shell-options

Conversion should honor this and set the proper shell.

Also, since circle's default shell is `/bin/bash`, we should set `shell: Bash` for any run step that doesn't specify a shell.

**Comment by jimsheldon** [comment]
Here are some conversion examples of what we want:

## Example 1

### Source

```yaml
jobs:
  build-push:
    docker:
      - image: alpine:3.11
    shell: /bin/sh -leo pipefail
    steps:
      - checkout
      - run:
          name: env
          command: |-
            env
workflows:
  build-push:
    jobs:
      - build-push
```

### v1 Result

```yaml
stages:
- name: build-push
  spec:
    platform:
      arch: amd64
      os: linux
    runtime:
      spec: {}
      type: cloud
    steps:
    - name: env
      spec:
        image: alpine:3.11
        run: |
          set -leo pipefail
          env
        shell: sh
      type: script
  type: ci
version: 1
```

### v0 Result

```shell
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: buildpush
      name: build-push
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: env
              name: env
              shell: Sh
              spec:
                command: |
                  set -leo pipefail
                  env
                image: alpine:3.11
              timeout: ""
              type: Run
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```
