### ISSUE TITLE
[downgrade] stage-level environment variables do not convert correctly

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#139]
Here is an example v1 yaml
```yaml
stages:
- name: test
  spec:
    envs:
      STAGE_VARIABLE: value
    platform:
      arch: amd64
      os: linux
    runtime:
      spec: {}
      type: cloud
    steps:
    - name: hello
      spec:
        image: busybox
        run: |
          echo hello
        shell: bash
      type: script
  type: ci
version: 1
```
which converts to this v0 yaml
```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: test
      name: test
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              envVariables:
                STAGE_VARIABLE: value
              identifier: hello
              name: hello
              spec:
                command: |
                  echo hello
                image: busybox
                shell: Bash
              timeout: ""
              type: Run
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```
`envVariables` is not valid at this level, `STAGE_VARIABLE` is not available to the `hello` step shell commands.

It should convert to this v0 yaml

```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: test
      name: test
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: hello
              name: hello
              spec:
                command: |
                  echo hello
                image: busybox
                shell: Bash
              timeout: ""
              type: Run
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
      variables:
      - name: STAGE_VARIABLE
        type: String
        description: ""
        required: false
        value: value
```

Valid values for `type` are `String`, `Secret` and `Number`, I think we only need to worry about `String` and `Number`. We might be able to get away with treating everything as `String` with double quotes and not worry about `Number`.
