### ISSUE TITLE
[drone] Support triggers and conditions

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#14]
Drone [triggers](https://docs.drone.io/pipeline/triggers/) can be set at the pipeline level.

Drone [conditions](https://docs.drone.io/pipeline/conditions/) can be set at the step level.

The conversion process needs to support both.

## Example trigger

Drone yaml
```yaml
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
```

Downgraded Harness yaml
```yaml
pipeline:
  name: default
  identifier: default
  stages:
    - stage:
        type: CI
        spec:
          execution:
            steps:
        when:
          pipelineStatus: Success
          condition: <+codebase.sourceBranch> == "master" # is there a better variable than codebase.sourceBranch?
```

## Example condition

Drone yaml
```yaml
kind: pipeline
type: docker
name: default

steps:
  - name: hello
    image: busybox
    commands:
    - echo hello
    when:
      event:
        exclude:
          - pull_request
```

Downgraded Harness yaml
```yaml
pipeline:
  name: default
  identifier: default
  stages:
    - stage:
        name: One
        identifier: One
        description: ""
        type: CI
        spec:
          execution:
            steps:
              - step:
                  when:
                    stageStatus: Success
                    condition: <+trigger.event> != "PR" # is there a better variable than trigger.event?
                  type: Run
                  name: hello
                  identifier: hello
                  spec:
                    shell: Sh
                    command: echo hello
```
