### ISSUE TITLE
[downgrade] quoted keys breaks conversion

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#169]
Here is a v1 pipeline with a quoted key (to make sure `on` is treated as a string rather than a boolean)
```yaml
stages:
- name: test
  spec:
    steps:
    - name: job1
      "on":
        failure:
          errors:
          - all
          type: ignore
      spec:
        run: execute_script_1
      type: script
  type: ci
version: 1
```
Currently this fails to downgrade
```
2023/08/16 10:14:24 unexpected end of JSON input
```
Removing the double quotes around `on` converts successfully.

`downgrade` needs to allow for keys that are in double quotes.
