### ISSUE TITLE
[drone] `depends_on` not handled

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#17]
Drone supports [parallelism](https://docs.drone.io/pipeline/docker/syntax/parallelism/) at the pipeline and step level with `depends_on`. Setting `depends_on` at the pipeline or step level currently seems to have no effect on the converted yaml. 

## Example

This pipeline has three stages. The first two stages should run in parallel, if they succeed, the third pipeline should run. Steps one and two in the first stage should also run in parallel, if they succeed, the third step should run.

```yaml
kind: pipeline
type: docker
name: first

steps:
- name: one
  image: busybox
  commands:
  - echo one
- name: two
  image: busybox
  commands:
  - echo two
- name: three
  image: busybox
  commands:
  - echo three
  depends_on:
  - one
  - two

---
kind: pipeline
type: docker
name: second

steps:
- name: one
  image: busybox
  commands:
  - echo one

---
kind: pipeline
type: docker
name: third

depends_on:
- first
- second

steps:
- name: one
  image: busybox
  commands:
  - echo one
```
