### ISSUE TITLE
[drone] `platform` not handled consistently

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#18]
The `platform` parameter is not converted consistently.

### Linux/arm64

```yaml
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: hello
  image: busybox
  commands:
  - echo hello
```

Conversion to new Harness YAML:

```
./go-convert drone example.yaml
options: {}
stages:
- name: default
  spec:
    clone: {}
    platform:
      arch: arm64
      os: linux
    runtime:
      spec: {}
      type: machine
    steps:
    - name: hello
      spec:
        image: busybox
        run: echo hello
      type: script
  type: ci
```

The above conversion set `arm64` as expected.

Conversion to old Harness YAML:

```
./go-convert drone -downgrade example.yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: default
      name: default
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: hello
              name: hello
              spec:
                command: echo hello
                image: busybox
              timeout: ""
              type: Run
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```

The above converted yaml has `Amd64` which is wrong.

### Windows/amd64

```yaml
kind: pipeline
type: docker
name: default

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: hello
  image: busybox
  commands:
  - echo hello
```

Conversion to new Harness YAML:

```
options: {}
stages:
- name: default
  spec:
    clone: {}
    platform:
      arch: amd64
      os: windows
    runtime:
      spec: {}
      type: machine
    steps:
    - name: hello
      spec:
        image: busybox
        run: echo hello
      type: script
  type: ci
```

The above conversion set `windows` as expected.

NOTE: Should there be a warning that `version` is no longer a supported field?

Conversion to old Harness YAML:

```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: default
      name: default
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: hello
              name: hello
              spec:
                command: echo hello
                image: busybox
              timeout: ""
              type: Run
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```

The above converted yaml has `Linux` which is wrong.
