### ISSUE TITLE
[travis] support triggers and condition

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-convert#19]
travis supports defining conditional pipeline execution logic directly in the yaml:

```
# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable
```

this is also supported by drone, circle, azure, gitlab, github and more.  we should treat this as a major product gap.
