### ISSUE TITLE
[travis] support for customizing the vm image

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-convert#26]
Travis currently defines a `dist` field that allows customizing the os version:

```yaml
dist:
  type: string
  enum:
  - trusty
  - precise
  - xenial
  - bionic
  - server-2016
```

Example:

```yaml
dist: xenial
```

Examples from docs:
* https://docs.travis-ci.com/user/reference/linux/#using-xenial
