### ISSUE TITLE
[github] support for `jobs.<job_id>.services.<service_id>.options`

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#30]
Additional Docker container resource options.

See
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservices

Example

```yaml
name: service

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >- # TODO: investigate conversion
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: docker ps
        run: docker ps
```
