### ISSUE TITLE
[downgrade] downgrader does not convert `steps.spec.ports`

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#31]
Example github workflow

```yaml
name: service

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        # Map port 8080 on the Docker host to port 80 on the nginx container
        ports:
          - 8080:80
```

Default conversion
```yaml
name: service
stages:
- name: test
  spec:
    platform:
      arch: amd64
      os: linux
    runtime:
      spec: {}
      type: cloud
    steps:
    - name: nginx
      spec:
        image: nginx
        ports:
        - 8080:80
      type: background
  type: ci
version: 1
```

Downgraded conversion
```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: test
      name: test
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: nginx
              name: nginx
              spec:
                image: nginx
              timeout: ""
              type: Background
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```

I feel this should convert to
```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: test
      name: test
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: nginx
              name: nginx
              spec:
                image: nginx
                portBindings:
                  "8080": "80"
              timeout: ""
              type: Background
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```

NOTE: `portBindings` requires both host and container ports, other providers support passing in a single port. In that case I think our conversion should set both host and container ports to the same value.

GitHub also supports the port protocol, for example

```yaml
    ports:
      - 6379/tcp
```

Maybe we are safe to convert this since TCP is the default? I'm not sure what the behavior should be for UDP.
