### ISSUE TITLE
[github] support `jobs.<job_id>.timeout-minutes`

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#44]
The maximum number of minutes to let a job run before GitHub automatically cancels it. Default: 360

We will likely need to convert to a string (`30` should probably be `30m`), but we will need to verify.

See
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

**Comment by jimsheldon** [comment]
I started to write a test case which should work at the step level, but not the stage level.

```yaml
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        with:
          command: npm run expect -- --env lastName=Smith
        env:
          CYPRESS_firstName: Joe
```

`.golden`
```yaml
name: timeouts
stages:
- name: cypress-run
  spec:
    clone: {}
    platform:
      arch: amd64
      os: linux
    runtime:
      spec: {}
      type: cloud
    steps:
    - name: Cypress run
      spec:
        envs:
          CYPRESS_firstName: Joe
        uses: cypress-io/github-action@v2
        with:
          command: npm run expect -- --env lastName=Smith
      timeout: 5m
      type: action
  type: ci
version: 1
```
