### ISSUE TITLE
[downgrade] action `env` convert error

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#50]
Example GitHub Actions yaml:

```yaml
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: $MESSAGE
        env:
          MESSAGE: world
```

Converted downgraded yaml:
```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: job1
      name: job1
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: echo
              name: echo
              spec:
                evn:
                  MESSAGE: world
                uses: actions/hello-world-javascript-action@main
                with:
                  who-to-greet: $MESSAGE
              timeout: ""
              type: Action
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```

`evn` should be `env`.
