### ISSUE TITLE
[downgrade] environment variables with invalid characters

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#55]
Example github yaml

```yaml
env:
  my-key: my-value
```

Converted, downgraded yaml
```yaml
      variables:

      - name: my-key
        type: String
        value: my-value
```

`my-key` has a `-` character which is invalid in Harness CI.
