### ISSUE TITLE
Drone downgrade does not honor `-project` flag

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#6]
## Steps to reproduce

1. Create `example.yml`
   ```yaml
   kind: pipeline
   name: example
   type: docker

   steps:
   - name: echo
     image: busybox
     commands: [echo hello]
   ```
2. Run `go-convert`
   ```
   $ go-convert drone -downgrade -project example example.yml
   pipeline:
     identifier: default
     name: default
     orgIdentifier: default
     projectIdentifier: default
     properties:
       ci:
         codebase:
           build: <+input>
     stages:
     - stage:
         identifier: example
         name: example
         spec:
           cloneCodebase: true
           execution:
             steps:
             - step:
                 identifier: echo
                 name: echo
                 spec:
                   command: echo hello
                   image: busybox
                 timeout: ""
                 type: Run
           platform:
             arch: Amd64
             os: Linux
           runtime:
             spec: {}
             type: Cloud
         type: CI
   ```
Notice that `projectIdentifier` is `default` when it should be `example`.
