### ISSUE TITLE
[bitbucket] conditional steps and changesets attribute

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-convert#8]
Harness currently supports limiting Pipeline execution based on changed files, however, this is only supported through triggers. It is not support at the Stage or Step level. Here is an example of the Bitbucket syntax at the stage level [1]:

```yaml
pipelines:
   default:
    - stage:
        name: Build and test
        condition:
          changesets:
            includePaths:
              # only xml files directly under path1 directory
              - "path1/*.xml"
              # any changes in deeply nested directories under path2
              - "path2/**"
```

And here is an example at the Step level:

```yaml
pipelines:
  default:
    - step:
        name: step1
        script:
            - echo "failing paths"
            - exit 1
        condition:
            changesets:
                includePaths:
                  # only xml files directly under path1 directory
                  - "path1/*.xml"
                  # any changes in deeply nested directories under path2
                  - "path2/**"
```

[1] https://support.atlassian.com/bitbucket-cloud/docs/stage-options/#Changesets
[2] https://support.atlassian.com/bitbucket-cloud/docs/step-options/#Condition-changesets
