### ISSUE TITLE
[downgrade] conditions logic is not accurate

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#80]
Some of the downgrade condition/trigger logic is wrong.

For example, `<+codebase.commitRef> =~ "refs/heads/master"` is not valid, it should be `<+codebase.commitRef> == "refs/heads/master"`.

We need to investigate the correct condition and trigger logic.

**Comment by jimsheldon** [comment]
I think we need logic that can handle wildcards.

For example, we can have a drone condition like this:

```yaml
- name: example
  image: alpine
  commands: echo example
  when:
    branch:
    - example-*
```

To do this in JEXL, we need to use `=~` like this:

```
<+trigger.branch> =~ "example-.*"
```

But a drone pipeline like this:

```yaml
- name: example
  image: alpine
  commands: echo example
  when:
    branch:
    - example
```

Would use JEXL like this:

```
To do this in JEXL, we need to use `=~` like this:

```
<+trigger.branch> == "example"
```
