### ISSUE TITLE
[downgrade] support `steps.spec.ports`

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#86]
Example GitHub yaml

```yaml
name: service

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        # Map port 8080 on the Docker host to port 80 on the nginx container
        ports:
          - 8080:80
```

Converts to this v1 yaml with `ports` set correctly

```yaml
name: service
stages:
- name: test
  spec:
    platform:
      arch: amd64
      os: linux
    runtime:
      spec: {}
      type: cloud
    steps:
    - name: nginx
      spec:
        image: nginx
        ports:
        - 8080:80
      type: background
  type: ci
version: 1
```

Ports are lost when downgrading to v0 yaml

```yaml
pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: test
      name: test
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: nginx
              name: nginx
              spec:
                image: nginx
              timeout: ""
              type: Background
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
```

The step should downgrade to this

```yaml
              - step:
                  type: Background
                  name: nginx
                  identifier: nginx
                  spec:
                    image: nginx
                    portBindings:
                      8080: "80"
```

NOTE: the port binding is not an int, it is a string, so quotes are required
