### ISSUE TITLE
[bitbucket] multiple caches and granular cache keys

### ISSUE THREAD

**Issue by bradrydzewski** [drone/go-convert#9]
Bitbucket supports multiple caches and granular cache keys. Example:

```yaml
definitions:
  caches:
    my-bundler-cache:
      key:
        files:
          - Gemfile.lock
          - "**/*.gemspec"
      path: vendor/bundle
    my-npm-cache:
      key:
        files:
          - package.json
      path: node_modules
```
