### ISSUE TITLE
[downgrade] wrong downgraded expressions

### ISSUE THREAD

**Issue by jimsheldon** [drone/go-convert#90]
We need to verify that triggers and other expressions downgrade properly.

For example, pull requests currently convert to `<+trigger.event> == "pull_request"` or `<+trigger.event> != "pull_request"`, but `pull_request` is not valid, it should be `PR`.

**Comment by eoinmcafee00** [comment]
hey @jimsheldon - can you add some test examples to a branch for this issue? That way I know what to target.

**Comment by jimsheldon** [comment]
Let's focus on `event` first.

Drone supports event conditions like this:

```yaml
# exclude pull_request events
when:
  event:
    exclude:
    - pull_request
```

```yaml
when:
  event:
    include:
    - push
    - tag
```

Downgraded Harness yaml should look like this:

|drone|downgrade|
|-----|---------|
| exclude `pull_request` events | `<+trigger.event> != "PR"` |
| include `push` events | `<+trigger.event> == "PUSH"` |
| include `tag` events | `<+trigger.payload.ref> =~ "refs/tags/.*"` |

Note that I believe `trigger.payload.ref` is specific to GitHub, I'm not sure how other providers structure their payloads (let's focus on GitHub first).
